apiVersion: v1
kind: Service
metadata:
  name: go-app-svc-db
  labels:
    app: esraa-go-app-svc-db
spec:
  ports:
    - port: 80
      targetPort: 3306
      protocol: TCP
  selector:
    app: esraa-go-app-db
