apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
  labels:
    app: esraa-go-app-svc
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: esraa-go-app
